season = "2023-24"

team_names_men = ["Calcit Volley",
                "FužinarSijMetalRavne",
                "HišaNaKolesihTriglav",
                "Alpacem Kanal",
                "ACH Volley Ljubljana",
                "Krka",
                "Merkur Maribor",
                "Panvita Pomgrad"]
team_names_women = ["Calcit Volley",
                    "Nova KBM Branik",
                    "ATK Grosuplje",
                    "GEN-I Volley",
                    "OD Krim",
                    "Ankaran",
                    "SIP Šempeter",
                    "Formis"]
team_names = team_names_men + team_names_women

teams_men = {
    "Calcit Volley" : {"1": "Planinšič Uroš",
                       "2": "Mujanović Nik",
                       "5": "Vinkovič Dino",
                       "6": "Lazar Luka",
                       "8": "Klobučar Jan",
                       "9": "Karadža Pevc Matevž",
                       "10": "Košenina Alan",
                       "11": "Nikolić Uroš",
                       "12": "Okroglič Jure",
                       "13": "Bošnjak Črtomir",
                       "15": "Mitrašinović Tomislav",
                       "16": "Brunet Llanes Lazaro Yoelvis",
                       "17": "Oman Jurij",
                       "18": "Bakonji Bernard",
                       "77": "Pavlovič Uroš"},
    "FužinarSijMetalRavne": {"1": "Pušnik Tilen",
                             "2": "Križanič Bor",
                             "3": "Lednik Nace",
                             "4": "Robida Denis",
                             "6": "Ranc David",
                             "7": "Stojanov David",
                             "10": "Libnik Blaž",
                             "12": "Javornik Gregor",
                             "14": "Vučetić Luka",
                             "17": "Plesec Vasja",
                             "18": "Podričnik Tine",
                             "20": "Drevenšek Matic",
                             "23": "Zmagaj Nace",
                             "27": "Hribernik Nejc"},
    "HišaNaKolesihTriglav": {"1": "Maček Jan",
                             "3": "Andovski Hristijan",
                             "4": "Nanut Maj",
                             "5": "Peruničić Nemanja",
                             "6": "Tučen Uroš",
                             "7": "Fajfar Matic",
                             "11": "Snedec Amadej",
                             "12": "Šikanič Aljoša",
                             "13": "Mali Miha",
                             "14": "Adžović Adi",
                             "15": "Jovović Đorđe",
                             "16": "Zalokar Nejc",
                             "19": "Jančič Jan Karl"},
    "Alpacem Kanal":  {"1": "Kodrič Erik",
                       "2": "Stojanovič Aleksander",
                       "3": "Cafuta Miha",
                       "5": "Jakovac Karlo",
                       "6": "Karnel Irenej",
                       "8": "Godnič Jani",
                       "9": "Kavčič Jakob",
                       "10": "Maretič Lian Svit",
                       "12": "Okroglič Grega",
                       "14": "Blazsovics Peter",
                       "15": "Vrtovec Matic",
                       "23": "Ranc Vid"},
    "ACH Volley Ljubljana": {"1": "Mejal Primož",
                             "3": "Kržič Jošt",
                             "4": "Satler Rok",
                             "5": "Šket Alen",
                             "8": "Marovt Luka",
                             "9": "Šen Klemen",
                             "11": "Koncilja Danijel",
                             "13": "Kovačič Jani",
                             "14": "Gjorgiev Nikola",
                             "15": "Sešek Jaka",
                             "16": "Pokeršnik Jan",
                             "17": "Videčnik Matic"},
    "Krka": {"2": "Medved Gal",
             "3": "Erpič Grega",
             "4": "Kocjančič Jure",
               "5": "Kosmina Martin",
               "7": "Bregar Miha",
               "8": "Verdinek Jožef",
               "9": "Kožar Nejc",
               "10": "Pulko Zlatko",
               "11": "Erpič Uroš",
               "14": "Lindič Luka",
               "15": "Kern Cameron",
               "23": "Rojnik Matic",
               "27": "Jakše Erazem"},
    "Merkur Maribor": {"2": "Fužir Urban",
                       "3": "Vodušek Timotej",
                       "4": "Pernuš Gregor",
                       "5": "Adžović Sani",
                       "6": "McConnell Connor",
                       "7": "Valenčič Martin",
                       "8": "Bračko Rok",
                       "9": "Kumer Žiga",
                       "10": "Kržič Janž Janez",
                       "11": "Donik Žiga",
                       "13": "Fink Miha",
                       "20": "Novak Marin"},
    "Panvita Pomgrad": {"1": "Rajnar Urban",
                        "4": "Doda Leonardo",
                        "5": "Šormaz Nenad",
                        "7": "Drvarič Urban",
                        "8": "Vrabl Tin",
                        "9": "Suhadolnik Vid",
                        "11": "Horvat Žiga",
                        "12": "Legen Nik",
                        "14": "Bedrač Žan",
                        "16": "Novak David",
                        "17": "Mirković Stefan",
                        "18": "Miko Luka"},
}

teams_women = {
    "ATK Grosuplje": {"2": "Gorjup Ula",
                      "3": "Gojković Nadja",
                      "6": "Krašovec Zala",
                      "8": "Boben Rusić Zoja",
                      "9": "Šen Asja",
                      "10": "Kukman Naja",
                      "11": "Žužek Lana",
                      "12": "Pucelj Nika",
                      "13": "Filipič Tara",
                      "14": "Gornjec Hodnik Ajda",
                      "15": "Čož Klavdija",
                      "17": "Križman Kaja"},
    "GEN-I Volley": {"3": "Damjanović Sanja",
                     "4": "Frelih Polona",
                     "5": "Pertens Silvia",
                     "6": "Marušič Polona",
                     "9": "Rituper Lara",
                     "10": "Jelina Ula",
                     "11": "Blažič Pia",
                     "12": "Marušič Špela",
                     "13": "Makuc Gaja",
                     "15": "Mazej Anja",
                     "16": "Mohorič Julija",
                     "17": "Žigon Ana"},
    "OD Krim": {"1": "Mohorič Katjuša",
                "4": "Friškovec Tara",
                "5": "Zalokar Iza",
                "6": "Čotar Nika",
                "8": "Križnik Daša",
                "9": "Jovanović Maja",
                "10": "Kranjec Neja",
                "13": "Đukić Sara",
                "15": "Bogataj Laura",
                "16": "Jerman Alja",
                "18": "Janjić Maša",
                "61": "Belič Pia"},
    "Ankaran": {"2": "Kolenc Lajris",
                "3": "Jamnik Pregl Nika",
                "4": "Grbas Mia",
                "5": "Labinjan Živa",
                "6": "Kovačič Maja",
                "7": "Grudina Tina",
                "8": "Forštnarič Maja",
                "9": "Žnidar Anastazija",
                "10": "Valencic Sara",
                "11": "Cerovac Tara",
                "14": "Pangerc Ema",
                "17": "Kaker Tina"},
    "Calcit Volley": {"2": "Griljc Živa",
                      "7": "Radišković Andjelka",
                      "8": "Stojiljković Nina",
                      "9": "Vovk Ana Marija",
                      "10": "Đorđević Mila",
                      "12": "Boisa Naja",
                      "13": "Kregar Klara",
                      "14": "Charuk Lucille June",
                      "15": "Sillah Fatoumatta",
                      "16": "Vukojević Adriana",
                      "18": "Pucelj Maša",
                      "19": "Čižman Neja",
                      "20": "Banko Katja"},
    "Nova KBM Branik": {"1": "Mlakar Iza",
                        "2": "Milošič Klara",
                        "3": "Pogačar Eva",
                        "7": "Štampar Ronja",
                        "8": "Klajžar Daša",
                        "9": "Lekše Tali",
                        "11": "Senekovič Pia",
                        "12": "Cikač Urška",
                        "13": "Farkaš Anja",
                        "16": "Potokar Monika",
                        "17": "Lorber Fijok Lorena",
                        "18": "Kranjc Ana Mojca"},
    "SIP Šempeter": {"2": "Lukman Lina",
                     "3": "Božič Maša",
                     "4": "Koren Tia",
                     "5": "Črnila Vita",
                     "7": "Vovk Anja",
                     "8": "Bavdaž Nika",
                     "9": "Vidali Neja",
                     "10": "Mašulović Nataša",
                     "14": "Lebič Maja",
                     "17": "Kadunc Ira"},
    "Formis": {"3": "Vodušek Tjana",
               "4": "Škoflek Adela",
               "5": "Cvetko Daša",
               "7": "Šteharnik Tinkara",
               "8": "Zupan Lana",
               "9": "Godec Žana",
               "10": "Uršič Urša",
               "12": "Grubišič Čabo Julija",
               "13": "Milošič Nika",
               "14": "Divjak Naja",
               "16": "Klavžar Ema",
               "18": "Halužan Sagadin Žana",
               "21": "Bračič Neja"}
}
